title: Bootstrap Icons
description: "Official open source icon library for Bootstrap"
baseurl: ""
source: "./docs"

markdown: kramdown

package_version: 0.1.0
package_repo: https://github.com/twbs/icons/

current_version: "4.3.1"
docs_version:    "4.3"

main:            "https://getbootstrap.com/"
repo:            "https://github.com/twbs/bootstrap"
twitter:         "getbootstrap"
slack:           "https://bootstrap-slack.herokuapp.com"
blog:            "https://blog.getbootstrap.com"
expo:            "https://expo.getbootstrap.com"
icons:           "https://icons.getbootstrap.com"
themes:          "https://themes.getbootstrap.com"
